BlogicRM_/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace BlogicRM_.Models
{
    public class Client : GenericPerson
    { 
        [Key]
        public int ClientID { get; set; }

        public List<Contract> Contracts { get; set; }
    }
}

BlogicRM_/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogicRM_.Data;
using BlogicRM_.Models;
using System.Text;

namespace BlogicRM_.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BlogicRM _context;

        public ClientsController(BlogicRM context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index(string Filter)
        {
            var clients = _context.Client.AsQueryable();

            if (!String.IsNullOrEmpty(Filter))
            {
                clients = clients.Where(c => c.Name.Contains(Filter) || c.Surname.Contains(Filter));
                ViewData["Filter"] = Filter;
            }
            return View(await clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .Include(c => c.Contracts)
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,Name,Surname,Email,BirthNumber,Age,Phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,Name,Surname,Email,BirthNumber,Age,Phone")] Client client)
        {
            if (id != client.ClientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            _context.Client.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ExportToCSV()
        {
            var data = await _context.Client.ToListAsync();

            try
            {
                StringBuilder sb = new();
                sb.AppendLine("ID;Jméno;Příjmení;Email;Rodné číslo;Věk;Telefon");
                foreach (var c in data)
                {
                    sb.AppendLine(
                        $"{c.ClientID};" +
                        $"{c.Name};" +
                        $"{c.Surname};" +
                        $"{c.Email};" +
                        $"{c.BirthNumber};" +
                        $"{c.Age};" +
                        $"{c.Phone}"
                        );
                }
                return File(Encoding.UTF8.GetBytes(sb.ToString()), "text/csv", "BlogicRM_klienti_export.csv");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.ClientID == id);
        }
    }
}

BlogicRM_/Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogicRM_.Data;
using BlogicRM_.Models;
using System.Text;

namespace BlogicRM_.Controllers
{
    public class ContractsController : Controller
    {
        private readonly BlogicRM _context;

        public ContractsController(BlogicRM context)
        {
            _context = context;
        }

        // GET: Contracts
        public async Task<IActionResult> Index(string Filter)
        {
            var blogicRM = _context.Contract.Include(c => c.Administrator).Include(c => c.Client).Include(c => c.Institution);

            if (!String.IsNullOrEmpty(Filter))
            {
                blogicRM = _context.Contract.Where(c => c.EvidenceNumber.Contains(Filter)).Include(c => c.Administrator).Include(c => c.Client).Include(c => c.Institution);
                ViewData["Filter"] = Filter;
            }
            return View(await blogicRM.ToListAsync());
        }

        // GET: Contracts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.Administrator)
                .Include(c => c.Client)
                .Include(c => c.Institution)
                .FirstOrDefaultAsync(m => m.ContractID == id);
            Dictionary<int, string> advisors = FindAdvisors(id);
            if (contract == null)
            {
                return NotFound();
            }

            ViewData["Advisors"] = advisors;

            return View(contract);
        }

        // GET: Contracts/Create
        public IActionResult Create()
        {
            ViewData["AdministratorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName");
            ViewData["ClientID"] = new SelectList(_context.Client, "ClientID", "FullName");
            ViewData["InstitutionID"] = new SelectList(_context.Institution, "InstitutionID", "Name");
            return View();
        }

        // POST: Contracts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContractID,EvidenceNumber,InstitutionID,ClientID,AdministratorID,ConclusionDate,ValidityDate,EndDate")] Contract contract)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                _context.Add(new ContractAdvisor { ContractID = contract.ContractID, AdvisorID = contract.AdministratorID });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdministratorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName", contract.AdministratorID);
            ViewData["ClientID"] = new SelectList(_context.Client, "ClientID", "FullName", contract.ClientID);
            ViewData["InstitutionID"] = new SelectList(_context.Institution, "InstitutionID", "Name", contract.InstitutionID);
            return View(contract);
        }

        // GET: Contracts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            ViewData["AdministratorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName", contract.AdministratorID);
            ViewData["ClientID"] = new SelectList(_context.Client, "ClientID", "FullName", contract.ClientID);
            ViewData["InstitutionID"] = new SelectList(_context.Institution, "InstitutionID", "Name", contract.InstitutionID);
            return View(contract);
        }

        // POST: Contracts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContractID,EvidenceNumber,InstitutionID,ClientID,AdministratorID,ConclusionDate,ValidityDate,EndDate")] Contract contract)
        {
            if (id != contract.ContractID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.ContractID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (!(_context.contractAdvisor.Any(ca => ca.ContractID == id && ca.AdvisorID == contract.AdministratorID)))
                {
                    _context.Add(new ContractAdvisor { ContractID = id, AdvisorID = contract.AdministratorID });
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdministratorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName", contract.AdministratorID);
            ViewData["ClientID"] = new SelectList(_context.Client, "ClientID", "FullName", contract.ClientID);
            ViewData["InstitutionID"] = new SelectList(_context.Institution, "InstitutionID", "Name", contract.InstitutionID);
            return View(contract);
        }

        // GET: Contracts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.Administrator)
                .Include(c => c.Client)
                .Include(c => c.Institution)
                .FirstOrDefaultAsync(m => m.ContractID == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Contracts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _context.Contract.FindAsync(id);
            var advisors = _context.contractAdvisor.Where(c => c.ContractID == id);
            foreach (var advisor in advisors)
            {
                _context.contractAdvisor.Remove(advisor);
            }
            await _context.SaveChangesAsync();
            _context.Contract.Remove(contract);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Contracts/Advisors/5
        public async Task<IActionResult> Advisors(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"].ToString();
                TempData.Remove("message");
            }

            var contract = await _context.Contract.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            Dictionary<int, string> advisors = FindAdvisors(id);
            ViewData["Advisors"] = advisors;
            ViewData["AdvisorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName");
            //ViewData["AdministratorID"] = new SelectList(_context.Advisor, "AdvisorID", "FullName", contract.AdministratorID);
            return View(contract);
        }

        // POST: Contracts/Advisors/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAdvisor(int id, int advisorId)
        {
            if (ModelState.IsValid)
            {
                if (_context.contractAdvisor.Any(ca => ca.ContractID == id && ca.AdvisorID == advisorId))
                {
                    TempData["message"] = "Vybraný poradce již je k této smlouvě přiřazen";
                    return RedirectToAction("Advisors", new { id });
                }
                _context.Add(new ContractAdvisor { ContractID = id, AdvisorID = advisorId });
                await _context.SaveChangesAsync();
                return RedirectToAction("Advisors", new { id });
            }
            return RedirectToAction("Advisors", new { id });
        }

        // POST: Contracts/DeleteAdvisor/5?advisorId=1
        [HttpPost, ActionName("DeleteAdvisor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAdvisor(int id, int advisorId)
        {
            var record = await _context.contractAdvisor.Where(ca => ca.ContractID == id).Where(ca => ca.AdvisorID == advisorId).FirstAsync();
            if (_context.Contract.Any(c => c.AdministratorID == advisorId))
            {
                TempData["message"] = "Vybraného poradce nelze smazat, protože je správcem smlouvy";
                return RedirectToAction("Advisors", new { id });
            }
            _context.contractAdvisor.Remove(record);
            await _context.SaveChangesAsync();
            return RedirectToAction("Advisors", new { id });
        }

BlogicRM_/Views/Clients/Create.cshtml
@model BlogicRM_.Models.Client

@{
    ViewData["Title"] = "Vytvořit klienta";
}

<h1>@ViewBag.Title</h1>

<h4>Klient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthNumber" class="control-label"></label>
                <input asp-for="BirthNumber" class="form-control" />
                <span asp-validation-for="BirthNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@ViewBag.Title" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Zpět na seznam klientů</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogicRM_/Views/Clients/Delete.cshtml
@model BlogicRM_.Models.Client

@{
    ViewData["Title"] = "Smazat klienta";
}

<h1>@ViewBag.Title</h1>

<h3>Opravdu chcete smazat tohoto klienta?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientID" />
        <input type="submit" value="@ViewBag.Title" class="btn btn-danger" /> |
        <a asp-action="Index">Zpět na seznam klientů</a>
    </form>
</div>

BlogicRM_/Views/Clients/Details.cshtml
@model BlogicRM_.Models.Client

@{
    ViewData["Title"] = "Podrobnosti";
}

<h1>@ViewBag.Title</h1>

<div>
    <h4>Klient</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    @if (Model.Contracts.Count != 0)
    {
        <h6 class="font-weight-bold">Klientovy smlouvy</h6>
        <hr />
        <ul class="list-group list-group">
            @foreach (var contract in Model.Contracts)
            {
                <li class="list-group-item list-group-item-action">
                    <a asp-controller="Contracts" asp-action="Details" asp-route-id="@contract.ContractID">Evidenční číslo: @contract.EvidenceNumber</a>
                </li>
            }
        </ul>
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ClientID">Upravit</a> |
    <a asp-action="Index">Zpět na seznam klientů</a>
</div>

BlogicRM_/Views/Clients/Edit.cshtml
@model BlogicRM_.Models.Client

@{
    ViewData["Title"] = "Upravit klienta";
}

<h1>@ViewBag.Title</h1>

<h4>Klient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClientID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthNumber" class="control-label"></label>
                <input asp-for="BirthNumber" class="form-control" />
                <span asp-validation-for="BirthNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@ViewBag.Title" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Zpět na seznam klientů</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogicRM_/Views/Clients/Index.cshtml
@model IEnumerable<BlogicRM_.Models.Client>

@{
    ViewData["Title"] = "Seznam klientů";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-action="Create">Vytvořit klienta</a> |
    <a asp-action="ExportToCSV">Exportovat klienty do CSV</a>
</p>

<div class="my-3">
    <form asp-for="Index" class="row g-2 mb-1">
        <div class="col-auto">
            <label for="search" class="form-label">Filtrovat klienty podle jména nebo příjmení</label>
        </div>
        <div class="col-auto">
            <input type="search" id="search" name="Filter" class="form-control">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Hledat</button>
        </div>
    </form>
    @if (ViewBag.Filter != null)
    {
        <p>Filtruji klienty odpovídající filtru <i>@ViewBag.Filter</i></p>
        <a asp-action="Index">Zobrazit úplný seznam</a>
    }
</div>

<table class="table table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ClientID">Upravit</a> |
                <a asp-action="Details" asp-route-id="@item.ClientID">Podrobnosti</a> |
                <a asp-action="Delete" asp-route-id="@item.ClientID">Smazat</a>
            </td>
        </tr>
}
    </tbody>
</table>