BlogicRM_/Models/Advisor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlogicRM_.Models
{
    public class Advisor : GenericPerson
    {
        [Key]
        public int AdvisorID { get; set; }

        [Display(Name = "Spravuje")]
        [InverseProperty("Administrator")]
        public List<Contract> Administering { get; set; }

        public ICollection<ContractAdvisor> Contracts { get; set; }
    }
}

BlogicRM_/Controllers/AdvisorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogicRM_.Data;
using BlogicRM_.Models;
using System.Text;

namespace BlogicRM_.Controllers
{
    public class AdvisorsController : Controller
    {
        private readonly BlogicRM _context;

        public AdvisorsController(BlogicRM context)
        {
            _context = context;
        }

        // GET: Advisors
        public async Task<IActionResult> Index(string Filter)
        {
            var advisors = _context.Advisor.AsQueryable();

            if (!String.IsNullOrEmpty(Filter))
            {
                advisors = advisors.Where(a => a.Name.Contains(Filter) || a.Surname.Contains(Filter));
                ViewData["Filter"] = Filter;
            }
            return View(await advisors.ToListAsync());
        }

        // GET: Advisors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advisor = await _context.Advisor
                .FirstOrDefaultAsync(m => m.AdvisorID == id);
            if (advisor == null)
            {
                return NotFound();
            }

            Dictionary<int, string> contracts = FindContracts(id);
            ViewData["Contracts"] = contracts;

            return View(advisor);
        }

        // GET: Advisors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Advisors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdvisorID,Name,Surname,Email,BirthNumber,Age,Phone")] Advisor advisor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(advisor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(advisor);
        }

        // GET: Advisors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advisor = await _context.Advisor.FindAsync(id);
            if (advisor == null)
            {
                return NotFound();
            }
            return View(advisor);
        }

        // POST: Advisors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdvisorID,Name,Surname,Email,BirthNumber,Age,Phone")] Advisor advisor)
        {
            if (id != advisor.AdvisorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(advisor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdvisorExists(advisor.AdvisorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(advisor);
        }

        // GET: Advisors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advisor = await _context.Advisor
                .FirstOrDefaultAsync(m => m.AdvisorID == id);
            if (advisor == null)
            {
                return NotFound();
            }

            return View(advisor);
        }

        // POST: Advisors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var advisor = await _context.Advisor.FindAsync(id);
            _context.Advisor.Remove(advisor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ExportToCSV()
        {
            var data = await _context.Advisor.ToListAsync();

            try
            {
                StringBuilder sb = new();
                sb.AppendLine("ID;Jméno;Příjmení;Email;Rodné číslo;Věk;Telefon");
                foreach (var a in data)
                {
                    sb.AppendLine(
                        $"{a.AdvisorID};" +
                        $"{a.Name};" +
                        $"{a.Surname};" +
                        $"{a.Email};" +
                        $"{a.BirthNumber};" +
                        $"{a.Age};" +
                        $"{a.Phone}"
                        );
                }
                return File(Encoding.UTF8.GetBytes(sb.ToString()), "text/csv", "BlogicRM_poradci_export.csv");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        private bool AdvisorExists(int id)
        {
            return _context.Advisor.Any(e => e.AdvisorID == id);
        }

        private Dictionary<int, string> FindContracts(int? id)
        {
            if (id == null)
            {
                return null;
            }

            var contracts = _context.contractAdvisor.Where(c => c.AdvisorID == id);
            Dictionary<int, string> contractDict = new Dictionary<int, string>();
            foreach (var contract in contracts)
            {
                var contractId = _context.Contract.Where(a => a.ContractID == contract.ContractID).First().ContractID;
                var contractEN = _context.Contract.Where(a => a.ContractID == contract.ContractID).First().EvidenceNumber;
                contractDict.Add(contractId, contractEN);
            }
            return contractDict;
        }
    }
}

BlogicRM_/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogicRM_.Data;
using BlogicRM_.Models;
using System.Text;

namespace BlogicRM_.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BlogicRM _context;

        public ClientsController(BlogicRM context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index(string Filter)
        {
            var clients = _context.Client.AsQueryable();

            if (!String.IsNullOrEmpty(Filter))
            {
                clients = clients.Where(c => c.Name.Contains(Filter) || c.Surname.Contains(Filter));
                ViewData["Filter"] = Filter;
            }
            return View(await clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .Include(c => c.Contracts)
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,Name,Surname,Email,BirthNumber,Age,Phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,Name,Surname,Email,BirthNumber,Age,Phone")] Client client)
        {
            if (id != client.ClientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            _context.Client.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ExportToCSV()
        {
            var data = await _context.Client.ToListAsync();

            try
            {
                StringBuilder sb = new();
                sb.AppendLine("ID;Jméno;Příjmení;Email;Rodné číslo;Věk;Telefon");
                foreach (var c in data)
                {
                    sb.AppendLine(
                        $"{c.ClientID};" +
                        $"{c.Name};" +
                        $"{c.Surname};" +
                        $"{c.Email};" +
                        $"{c.BirthNumber};" +
                        $"{c.Age};" +
                        $"{c.Phone}"
                        );
                }
                return File(Encoding.UTF8.GetBytes(sb.ToString()), "text/csv", "BlogicRM_klienti_export.csv");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.ClientID == id);
        }
    }
}

BlogicRM_/Controllers/InstitutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogicRM_.Data;
using BlogicRM_.Models;

namespace BlogicRM_.Controllers
{
    public class InstitutionsController : Controller
    {
        private readonly BlogicRM _context;

        public InstitutionsController(BlogicRM context)
        {
            _context = context;
        }

        // GET: Institutions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Institution.ToListAsync());
        }

        // GET: Institutions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institution = await _context.Institution
                .FirstOrDefaultAsync(m => m.InstitutionID == id);
            if (institution == null)
            {
                return NotFound();
            }

            return View(institution);
        }

        // GET: Institutions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Institutions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstitutionID,Name")] Institution institution)
        {
            if (ModelState.IsValid)
            {
                _context.Add(institution);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(institution);
        }

        // GET: Institutions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institution = await _context.Institution.FindAsync(id);
            if (institution == null)
            {
                return NotFound();
            }
            return View(institution);
        }

        // POST: Institutions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstitutionID,Name")] Institution institution)
        {
            if (id != institution.InstitutionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(institution);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstitutionExists(institution.InstitutionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(institution);
        }

        // GET: Institutions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institution = await _context.Institution
                .FirstOrDefaultAsync(m => m.InstitutionID == id);
            if (institution == null)
            {
                return NotFound();
            }

            return View(institution);
        }

        // POST: Institutions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var institution = await _context.Institution.FindAsync(id);
            _context.Institution.Remove(institution);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstitutionExists(int id)
        {
            return _context.Institution.Any(e => e.InstitutionID == id);
        }
    }
}

BlogicRM_/Views/Contracts/Advisors.cshtml
@model BlogicRM_.Models.Contract

@{
    ViewData["Title"] = "Poradci";
}

<h1>@ViewBag.Title</h1>

<div>
    <h4>Smlouva</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EvidenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EvidenceNumber)
        </dd>
    </dl>
</div>

<table class="table table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Advisors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (KeyValuePair<int, string> advisor in ViewBag.Advisors)
        {
            <tr>
                <td>
                    @advisor.Value
                </td>
                <td>
                    @using (Html.BeginForm("DeleteAdvisor", "Contracts", new { id = Model.ContractID, advisorId = advisor.Key }))
                    {
                        <input type="submit" value="Odstranit" class="btn btn-danger" onclick="return confirm('Opravdu chcete z této smlouvy odstranit poradce @advisor.Value');" />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddAdvisor">
            <div class="form-group">
                <input type="hidden" name="id" value="@Model.ContractID" />
                <label class="control-label">Poradce</label>
                <select name="advisorId" class="form-control" asp-items="ViewBag.AdvisorID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Přidat vybraného poradce" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@if (ViewBag.message != null)
{
    <div class="row">
        <div class="alert alert-danger">
            <p class="font-weight-bold">@ViewBag.message</p>
        </div>
    </div>
}


<div>
    <a asp-action="Details" asp-route-id="@Model.ContractID">Zobrazit smlouvu</a> |
    <a asp-action="Edit" asp-route-id="@Model.ContractID">Upravit smlouvu</a> |
    <a asp-action="Index">Zpět na seznam smluv</a>
</div>

BlogicRM_/Views/Contracts/Create.cshtml
@model BlogicRM_.Models.Contract

@{
    ViewData["Title"] = "Založit smlouvu";
}

<h1>@ViewBag.Title</h1>

<h4>Smlouva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EvidenceNumber" class="control-label"></label>
                <input asp-for="EvidenceNumber" class="form-control" />
                <span asp-validation-for="EvidenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstitutionID" class="control-label"></label>
                <select asp-for="InstitutionID" class ="form-control" asp-items="ViewBag.InstitutionID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientID" class="control-label"></label>
                <select asp-for="ClientID" class ="form-control" asp-items="ViewBag.ClientID"></select>
            </div>
            <div class="form-group">
                <label asp-for="AdministratorID" class="control-label"></label>
                <select asp-for="AdministratorID" class ="form-control" asp-items="ViewBag.AdministratorID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ConclusionDate" class="control-label"></label>
                <input asp-for="ConclusionDate" class="form-control" />
                <span asp-validation-for="ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidityDate" class="control-label"></label>
                <input asp-for="ValidityDate" class="form-control" />
                <span asp-validation-for="ValidityDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Založit smlouvu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Zpět na seznam smluv</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogicRM_/Views/Contracts/Delete.cshtml
@model BlogicRM_.Models.Contract

@{
    ViewData["Title"] = "Smazat smlouvu";
}

<h1>@ViewBag.Title</h1>

<h3>Jste si jisti, že chcete tuto smlouvu smazat?</h3>
<div>
    <h4>Contract</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EvidenceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EvidenceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConclusionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConclusionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidityDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidityDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Institution.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.FullName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Administrator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Administrator.FullName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContractID" />
        <input type="submit" value="Smazat smlouvu" class="btn btn-danger" /> |
        <a asp-action="Index">Zpět na seznam smluv</a>
    </form>
</div>

BlogicRM_/Views/Contracts/Details.cshtml
@model BlogicRM_.Models.Contract

@{
    ViewData["Title"] = "Podrobnosti";
}

<h1>@ViewBag.Title</h1>

<div>
    <h4>Smlouva</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EvidenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EvidenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ConclusionDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ConclusionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValidityDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValidityDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Institution)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Institutions" asp-action="Details" asp-route-id="@Model.InstitutionID">@Html.DisplayFor(model => model.Institution.Name)</a>
</dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Clients" asp-action="Details" asp-route-id="@Model.ClientID">@Html.DisplayFor(model => model.Client.FullName)</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Administrator)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Advisors" asp-action="Details" asp-route-id="@Model.AdministratorID">@Html.DisplayFor(model => model.Administrator.FullName)</a>
</dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Advisors)
        </dt>
        <dd class="col-sm-10">
            @foreach (KeyValuePair<int, string> advisor in ViewBag.Advisors)
            {
                <a asp-controller="Advisors" asp-action="Details" asp-route-id="@advisor.Key">@advisor.Value</a><br />
            }
        </dd>
        </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ContractID">Upravit</a> |
    <a asp-action="Advisors" asp-route-id="@Model.ContractID">Spravovat poradce</a> |
    <a asp-action="Index">Zpět na seznam smluv</a>
</div>

BlogicRM_/Views/Contracts/Edit.cshtml
@model BlogicRM_.Models.Contract

@{
    ViewData["Title"] = "Upravit smlouvu";
}

<h1>@ViewBag.Title</h1>

<h4>Contract</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContractID" />
            <div class="form-group">
                <label asp-for="EvidenceNumber" class="control-label"></label>
                <input asp-for="EvidenceNumber" class="form-control" />
                <span asp-validation-for="EvidenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstitutionID" class="control-label"></label>
                <select asp-for="InstitutionID" class="form-control" asp-items="ViewBag.InstitutionID"></select>
                <span asp-validation-for="InstitutionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientID" class="control-label"></label>
                <select asp-for="ClientID" class="form-control" asp-items="ViewBag.ClientID"></select>
                <span asp-validation-for="ClientID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdministratorID" class="control-label"></label>
                <select asp-for="AdministratorID" class="form-control" asp-items="ViewBag.AdministratorID"></select>
                <span asp-validation-for="AdministratorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConclusionDate" class="control-label"></label>
                <input asp-for="ConclusionDate" class="form-control" />
                <span asp-validation-for="ConclusionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidityDate" class="control-label"></label>
                <input asp-for="ValidityDate" class="form-control" />
                <span asp-validation-for="ValidityDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Upravit smlouvu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}